trigger:
- none

pool:
  name: Pipeline-2
  demands:
    - agent.name -equals Agent-1

stages:
  - stage: complie
    displayName: Maven Code Quality Check
    jobs:
      - job: maven
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Pipeline-project'
              mavenPomFile: 'pom.xml'
              goals: 'compile'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
      - job: test
        dependsOn: maven
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'Pipeline-project'
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      - job: trivy
        dependsOn: test
        steps:
          - task: CmdLine@2
            inputs:
              script: 'trivy fs --format table -o fs.html .'
      - job: sonarQube
        dependsOn: trivy
        steps:
          - task: SonarQubePrepare@8
            inputs:
              SonarQube: 'SonarQube-proj'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'BankApp'
              cliProjectName: 'BankApp'
              cliSources: '.'
              extraProperties: 'sonar.java.binaries=.'
          - task: SonarQubeAnalyze@8
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
      - job: snyk
        dependsOn: sonarQube
        steps:
        - script: |
                  snyk --version
                  npm install -g snyk-to-html
                  [ -f mvnw ] && chmod +x mvnw
                  mkdir -p result
                  snyk auth $SNYK_TOKEN
                  snyk test --all-projects --json-file-output=result/oss.json
                  snyk code test --sarif-file-output=result/sast.sarif
                  snyk-to-html -o result/oss.html < result/oss.json
                  snyk monitor --all-projects
          env:
            SNYK_TOKEN: $(SNYK_TOKEN)
            continueOnError: true
            displayName: 'Security Scan (Snyk)'
  - stage: publishArtifacts
    jobs:
      - job: publishArtifacts
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Pipeline-project'
              mavenPomFile: 'pom.xml'
              goals: 'deploy'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'maven'
          
  - stage: docker
    jobs:
      - job: dockerbuildandpush
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Dockerhub-pipeline'
              repository: 'gamertech1/bank-app'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: latest
             
