trigger:
- none

pool:
  name: Pipeline-2
  demands:
    - agent.name -equals Agent-1

stages:
  - stage: complie
    displayName: Maven Code Quality Check
    jobs:
      - job: maven
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'Pipeline-project'
              mavenPomFile: 'pom.xml'
              goals: 'compile'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
      - job: test
        steps:
        - task: Maven@4
          inputs:
            azureSubscription: 'Pipeline-project'
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
      - job: trivy
        steps:
          - task: CmdLine@2
            inputs:
              script: 'trivy fs --format table -o fs.html .'
      - job: sonarQube
        steps:
          - task: SonarQubePrepare@8
            inputs:
              SonarQube: 'SonarQube-proj'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'BankApp'
              cliProjectName: 'BankApp'
              cliSources: '.'
              extraProperties: 'sonar.java.binaries=.'
      - job: sonar
        steps:
          - task: SonarQubeAnalyze@8
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'